services:
  macats:
    build:
      context: .        # project root
      dockerfile: Dockerfile
    image: macats:latest
    env_file:
      - .env
    command: ["python3", "main.py"]
    restart: unless-stopped